# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on: 

  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  Run_workspace_Tests:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: List available Xcode versions
      run: ls /Applications | grep Xcode
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_12.2.app && /usr/bin/xcodebuild -version
    - name: simulators
      run: xcrun simctl list
    - name: Run unit tests
      run: xcodebuild test -scheme ButtonTap -project ButtonTap.xcodeproj -destination 'platform=iOS Simulator,name=iPhone 11,OS=14.2' | xcpretty && exit ${PIPESTATUS[0]}
