name: CI

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Build Project
    runs-on: macOS-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Select Xcode version
      run: sudo xcode-select -switch /Applications/Xcode_12.4.app
      
    - name: Build and test
      run: xcodebuild clean test -project ButtonTap.xcodeproj -scheme ButtonTap -sdk iphonesimulator -destination "platform=iOS Simulator,OS=14.4,name=iPhone 12" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO
