# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on: 

  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Build Project
    runs-on: macOS-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v1

    - name: Set Xcode version
      uses: maxim-lobanov/setup-xcode@v1.1
      with:
        xcode-version: 12.1

    - name: Build
      run: |
        set -o pipefail
        xcodebuild build \
        -scheme ButtonTap \
        -destination 'platform=iOS Simulator,name=iPhone 11 Pro' \
        | xcpretty
